#cloudbuilddev.yaml
steps:
#  - name: 'gcr.io/cloud-builders/docker'
#    args: ["build",'-t', 'gcr.io/$PROJECT_ID/api:latest',"-f" ,"./docker/api/Dockerfile","." ]
#  - name: 'gcr.io/cloud-builders/docker'
#    args: ["build",'-t', 'gcr.io/$PROJECT_ID/frontend:latest',"-f" ,"./docker/web-app/Dockerfile","."]
#  - name: 'gcr.io/cloud-builders/docker'
#      args: [ 'push', 'gcr.io/$PROJECT_ID/api:latest']
#  - name: 'gcr.io/cloud-builders/docker'
#      args: [ 'push', 'gcr.io/$PROJECT_ID/frontend:latest' ]
  - name: 'gcr.io/$PROJECT_ID/docker-compose'
    args: ["-f", "./docker/docker-compose.yml", "-f","./docker/dev.yml", 'build']
  - name: 'gcr.io/$PROJECT_ID/docker-compose'
    args: [ "-f", "./docker/docker-compose.yml", "-f","./docker/dev.yml", 'up' ]
#  - name: 'gcr.io/cloud-builders/docker'
#    args: ['tag', 'speech-emotion-webapp/api:latest', 'gcr.io/$PROJECT_ID/$REPO_NAME/api:$COMMIT_SHA']
#  - name: 'gcr.io/cloud-builders/docker'
#    args: ['tag', 'speech-emotion-webapp/frontend:latest', 'gcr.io/$PROJECT_ID/$REPO_NAME/frontend:$COMMIT_SHA']
#images: ['gcr.io/$PROJECT_ID/api:latest','gcr.io/$PROJECT_ID/frontend:latest']