#cloudbuilddev.yaml
steps:
  - name: 'docker/compose:1.19.0'
    args: ["-f", "./docker/docker-compose.yml", "-f","/.docker/dev.yml", 'up', '-d']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'workspace_app:latest', 'gcr.io/$PROJECT_ID/$REPO_NAME:latest']
images: ['gcr.io/$PROJECT_ID/$REPO_NAME:latest']