#cloudbuilddev.yaml
steps:
  - name: 'docker/compose:1.19.0'
    args: ["-f", "./docker/docker-compose.yml", "-f","/.docker/dev.yml", 'build','-t','swa_app:latest']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'swa_app:latest', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
images: ['gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']