version: "3.3"

networks:
  internal:
    external: false
services:
  backend:
    image: speech-emotion-webapp/api:latest
    environment:
      PYTHONPATH: /home/app/
    networks:
      - internal
    ports:
      - "8081:8081"
  frontend:
    environment:
      - BACKEND_HOSTNAME=backend
    image: speech-emotion-webapp/frontend:latest
    networks:
      - internal
    ports:
      - "3000:3000"