version: "3.3"

networks:
  internal:
    external: false
services:
  backend:
    image: speech-emotion-webapp/api:latest
    environment:
      PYTHONPATH: /home/app/src
    networks:
      - internal
    # command: "/home/app/wait-for-postgres.sh /home/app/start.sh"
    ports:
      - "8080:8080"
  frontend:
    environment:
      - BACKEND_HOSTNAME=backend
    image: speech-emotion-webapp/frontend:latest
    networks:
      - internal
    ports:
      - "3000:3000"