version: "3"

networks:
  internal:
    external: false

x-common-variables: &common-variables
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: test_db
  POSTGRES_HOST: db
  POSTGRES_PORT: 5432

services:
  db:
    image: postgres:11
    environment: *common-variables
    networks:
      - internal
  backend:
    build:
      context: ../
      dockerfile: $PWD/docker/api/Dockerfile
    image: speech-emotion-webapp/api:latest
    environment:
      <<: *common-variables
      PYTHONPATH: /home/app/src
    networks:
      - internal
    volumes:
      - $PWD/api:/home/app
    command: "/home/app/wait-for-postgres.sh /home/app/start.sh"
    ports:
      - "8081:8081"
    depends_on:
      - db
  frontend:
    environment:
      - BACKEND_HOSTNAME=backend
    build:
      context: ../
      dockerfile: $PWD/docker/web-app/Dockerfile
    image: speech-emotion-webapp/frontend:latest
    networks:
      - internal
    ports:
      - "3000:3000"
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
