version: "3.9"
services:
  backend:
    build: ./api
    image: speech-emotion-webapp/api:latest
    ports:
      - "8081:8081"
  frontend:
    build: ./web-app
    image: speech-emotion-webapp/frontend:latest
    ports:
      - "3000:3000"
