version: "3.3"

networks:
  internal:
    external: false
services:
  backend:
    build:
      context: ../
      dockerfile: $PWD/docker/api/Dockerfile
    image: speech-emotion-webapp/api:latest
    environment:
      PYTHONPATH: /home/app/src
    networks:
      - internal
    volumes:
      - $PWD/api:/home/app
    command: "/home/app/wait-for-postgres.sh /home/app/start.sh"
    ports:
      - "8081:8081"
  frontend:
    environment:
      - BACKEND_HOSTNAME=backend
    build:
      context: ../
      dockerfile: $PWD/docker/web-app/Dockerfile
    image: speech-emotion-webapp/frontend:latest
    networks:
      - internal
    ports:
      - "3000:3000"