version: "3.3"
services:
  backend:
    environment:
      CONFIG: prod
      POSTGRES_USER: ${POSTGRES_USER_PROD}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_PROD}
      POSTGRES_DB: ${POSTGRES_DB_PROD}
      POSTGRES_HOST: ${POSTGRES_HOST_PROD}
      POSTGRES_PORT: ${POSTGRES_PORT}