version: "3.3"
services:
  backend:
    build:
      context: ../
      dockerfile: $PWD/docker/api/Dockerfile
    command: "/home/app/wait-for-postgres.sh /home/app/start.sh"
    volumes:
      - $PWD/api:/home/app
    environment:
      CONFIG: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      - db
  frontend:
    build:
      context: ../
      dockerfile: $PWD/docker/web-app/Dockerfile
  db:
    image: postgres:11
    networks:
      - internal
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db

