version: "3.3"
services:
  backend:
    environment:
      CONFIG: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432