apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-ser-webapp-dev
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "ser-webapp-dev"
    networking.gke.io/managed-certificates: "certificate-ser-webapp-dev"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: www.speech-emotion-recognition.app
    http:
      paths:
        - path: /*
          backend:
            serviceName: service-ser-webapp-dev
            servicePort: 3000
        - path: /api/*
          backend:
            serviceName: service-ser-webapp-dev
            servicePort: 8081
  - host: dev.speech-emotion-recognition.app
    http:
      paths:
        - path: /*
          backend:
            serviceName: service-ser-webapp-test
            servicePort: 3000
        - path: /api/*
          backend:
            serviceName: service-ser-webapp-test
            servicePort: 8081
  - host: speech-emotion-recognition.app
    http:
      paths:
        - path: /*
          backend:
            serviceName: service-ser-webapp-dev
            servicePort: 3000
        - path: /api/*
          backend:
            serviceName: service-ser-webapp-dev
            servicePort: 8081