apiVersion: apps/v1
kind: Deployment
metadata:
  name: speech-webapp-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speech-webapp-test
  template:
    metadata:
      labels:
        app: speech-webapp-test
    spec:
      containers:
      - name: backend
        image: gcr.io/wewyse-centralesupelec-ftv/speech-web-app-dev/api:07d10ca9f7d0185af977f02f111474431dfdc1b7
        workingDir: /home/app
        ports:
        - containerPort: 8081
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /api/v0.1/get_random_sentence/
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 3
        env:
          - name: POSTGRES_HOST
            value: "10.69.192.6"
          - name: POSTGRES_DB
            value: "test_db"
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_USER
            value: "postgres"
          - name: RECAPTCHA
            valueFrom:
              secretKeyRef:
                name: recaptcha
                key: secret_key
          - name: CREDENTIALS_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: bucket-credentials
                key: private_key
          - name: CREDENTIALS_PRIVATE_KEY_ID
            valueFrom:
              secretKeyRef:
                name: bucket-credentials
                key: private_key_id
          - name: CREDENTIALS_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: bucket-credentials
                key: client_id
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-password-dev
                key: db_pass
          - name: PYTHONPATH
            value: '/home/app'
          - name: CONFIG
            value: 'test'
      - name: frontend
        image: gcr.io/wewyse-centralesupelec-ftv/speech-web-app-dev/frontend:07d10ca9f7d0185af977f02f111474431dfdc1b7
        ports:
        - containerPort: 3000
