apiVersion: apps/v1
kind: Deployment
metadata:
  name: speech-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speech-webapp
  template:
    metadata:
      labels:
        app: speech-webapp
        network/internal: "true"
    spec:
      containers:
      - name: backend
        image: gcr.io/wewyse-centralesupelec-ftv/speech-web-app/api@sha256:b377cae2137b3e69c5254b23111764c1e2ebb8e59b2f76d4ac88ce91d680da24
        workingDir: /home/app
        ports:
        - containerPort: 8081
        env:
          - name: POSTGRES_HOST
            value: "10.69.192.3"
          - name: POSTGRES_DB
            value: "test_db"
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-password-dev
                key: db_pass
          - name: PYTHONPATH
            value: '/home/app'
      - name: frontend
        image: gcr.io/wewyse-centralesupelec-ftv/speech-web-app/frontend@sha256:ed333c9d5f0e9be35280c9bf60596fa6172f6114d3e8dcef062f0496682b7716
        ports:
        - containerPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: internal
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              network/internal: "true"
  podSelector:
    matchLabels:
      network/internal: "true"
